### ISSUE TITLE
giv remote pick_coordinate crashes

### ISSUE THREAD

**Issue by simonkolotov** [dov/giv#51] opened 2018-02-15 05:08 UTC
Both the python version and the giv-command version fail after clicking on the giv screen:

```
Attempt to unlock mutex that was not locked

** (giv:2704): CRITICAL **: json_node_get_object: assertion 'node != NULL' failed

** (giv:2704): CRITICAL **: json_object_get_member: assertion 'object != NULL' failed

** (giv:2704): CRITICAL **: json_node_copy: assertion 'node != NULL' failed
[1]+  Aborted                 (core dumped) giv

```

**Comment by dov** [comment] 2018-02-15 05:18
Linux, windows, or both?

**Comment by simonkolotov** [comment] 2018-02-15 05:22
only tried on Linux. Can try on Windows tomorrow

**Comment by dov** [comment] 2018-02-15 08:04
Can't reproduce on HEAD. Please compile and try again.

**Comment by dov** [comment] 2018-04-01 18:36
Is this still a problem?

**Comment by simonkolotov** [comment] 2018-04-01 19:47
I don't remember, probably not. It must have been the wrong branch or
something.

In not really using it right now anyways.
Thanks though


Simon Kolotov

**Comment by dov** [comment] 2018-04-01 19:48
Ok. Closing it.

**Closed by dov** 2018-04-01 19:48 UTC
